### ISSUE TITLE
Debug error when closing after done

### ISSUE THREAD

**Issue by Jojo-1000** [planetchili/RoboMaze#1]
When I close the program in visual debug mode after it has finished, I get an error prompt:

> Debug Error!
> 
> Program: D:\C++\Repos\RoboMaze\x64\Debug\Engine.exe
> 
> abort() has been called

### Fix:
check if the future of DebugSimulator is valid before waiting / getting on it

```cpp
~DebugSimulator() override
{
    using namespace std::chrono_literals;
    if(future.valid())
    {
        // continuously signal go-ahead while future not ready
        while( future.wait_for( 500us ) != std::future_status::ready )
        {
            dc.SignalTick();
        }
        // complete the future
        future.get();
    }
}
```

**Comment by planetchili** [comment]
Already ahead of you bro, pushed that fix last night ;)
https://github.com/planetchili/RoboMaze/commit/02fe142041ba86c944969e4c2d0e4d111476fbb6

Thanks for the heads up though, don't hesitate to let me know if you find anything else.
